### PR TITLE
Add failing test for handshake with peer check

### PR DESCRIPTION
**Pull request by rohitpaulk**
In the handshake stage, we were setting the tracker URL to be the same as the peer, and hence the peer checks would return errors (they'd try to parse the tracker HTTP response as a handshake and error on the first byte). 

Most users haven't run into this so far because they don't hit the tracker in this stage - they'd just rely on the `peer` value we provide. A more realistic implementation would actually always fetch peers, and make sure the peer is in the list returned by the tracker, so we should handle this. Attached sample code that does this as a failing test.

Thanks to @MohamedAbdeen21 for highlighting this!

### CODE REVIEW

**Comment by sarp** [comment]
is this so that with the handshake command, trying to request peers will result in connection refused instead of wrong first byte error message?

**Comment by rohitpaulk** [comment]
@sarp quick ping on this in case it slipped through the cracks

**Comment by sarp** [comment]
thanks for the reminder. I have no objections to landing this change, looks good

as for supporting retrieval of peers during the test for connecting to a given IP:port, please help me understand the benefit would be to the user?

it feels like out of scope for this CLI command / test and I'd rather not add more complexity unless necessary

**Comment by rohitpaulk** [comment]
I don't mean to be too prescriptive here btw, any solution that you think fixes the issue that the user ran into would be okay. I thought that their concern was genuine - "I did this correctly, why are tests failing?"

**Comment by sarp** [comment]
no worries, makes sense. i'll look into this

**Pull request merged**
